modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="odmsttuf"
version="1.0.0"
displayName="ODMSttuf"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Dartanham, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.odmsttuf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.odmsttuf]]
    modId="manabarlib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.odmsttuf]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.odmsttuf]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration